sonar.projectKey=Ateliers-io_novasketch-frontend
sonar.organization=ateliers-io

sonar.sources=src
sonar.tests=src

# correctly classify tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# ⭐ removes duplication from tests
sonar.cpd.exclusions=**/*.test.*,**/*.spec.*

# coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# ignore generated files
sonar.exclusions=node_modules/**,dist/**,coverage/**